2.1 [BE] - Login using email and password
framgia/sph-els-dexter pull request #4
Opened 2023-01-17 06:49 UTC by Dixtir

[Asana Link]
[Task link](https://app.asana.com/0/1203660811930047/1203660813666005)

[Commands]
cd frontend 
npm run dev

cd backend
npm run dev

[Pre-Conditions]
None

[Expected Output]
To be able to authenticate the user on the backend side and return a token that will be used to access other APIs.

[Notes]
None

[Screenshots]
![Screenshot (1)](https://user-images.githubusercontent.com/121914102/212829110-ed379c4e-979d-4b18-94f3-459ca75f43c0.png)

2023-01-18 06:57 UTC, ejanton-sun requested changes

2023-01-18 06:57 UTC, ejanton-sun commented on backend/src/routes/quiz/quiz.model.ts
> +export default router
add new line

2023-01-18 06:57 UTC, ejanton-sun commented on backend/src/routes/user/user.controller.ts
> +        },
```suggestion
        data: {
          accessToken,
          refreshToken,
          expiresIn: EToken.EXPIRY
        },
```

2023-01-18 07:41 UTC, Dixtir commented on backend/src/routes/quiz/quiz.model.ts
> +export default router
fixed

2023-01-19 02:18 UTC, ejanton-sun approved these changes

2023-01-19 02:18 UTC, merged